# Generated by hand to optimize chat lookups.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['classroom', 'created_date'], name='message_classroom_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_date'], name='message_sender_created_idx'),
        ),
    ]
