# Generated by Django 6.0.4 on 2026-06-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_message_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chatting_me_classro_46d787_idx',
            old_name='message_classroom_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chatting_me_sender__505a61_idx',
            old_name='message_sender_created_idx',
        ),
    ]
