# Generated by Django 6.0.4 on 2026-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
