# Generated by Django 6.0.4 on 2026-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_lessonfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonfile',
            options={'verbose_name': 'LessonFile', 'verbose_name_plural': 'LessonFiles'},
        ),
    ]
