# Generated by Django 6.0.4 on 2026-05-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_lesson_options_alter_lessonfile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='checked',
        ),
    ]
