# Generated by Django 6.0.4 on 2026-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_application_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
