# Generated by Django 6.0.4 on 2026-05-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_course_slug_alter_lesson_slug'),
    ]

    operations = [
    migrations.RunSQL(
        sql="""
            CREATE INDEX IF NOT EXISTS idx_lesson_course ON community_lesson(course_id);
            CREATE INDEX IF NOT EXISTS idx_lessonfile_lesson ON community_lessonfile(lesson_id);
            CREATE INDEX IF NOT EXISTS idx_studying_user ON accounts_customuser_studying_in(customuser_id);
            CREATE INDEX IF NOT EXISTS idx_studying_course ON accounts_customuser_studying_in(course_id);
            CREATE INDEX IF NOT EXISTS idx_session_expire ON django_session(expire_date);
        """,
        reverse_sql="""
            DROP INDEX IF EXISTS idx_lesson_course;
            DROP INDEX IF EXISTS idx_lessonfile_lesson;
            DROP INDEX IF EXISTS idx_studying_user;
            DROP INDEX IF EXISTS idx_studying_course;
            DROP INDEX IF EXISTS idx_session_expire;
        """
    ),
    ]
