# Generated by Django 6.0.4 on 2026-05-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonFile',
        ),
    ]
