# Generated by Django 6.0.4 on 2026-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_delete_lessonfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not completed', 'Not Completed')], default='not completed', max_length=20),
        ),
    ]
