# Generated by Django 6.0.4 on 2026-05-30 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_course_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, default=[], related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
