# Generated by hand to optimize common query paths.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_classroom_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'accepted'], name='application_user_accepted_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'created_at'], name='course_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='course_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'created_at'], name='lesson_course_created_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['course', 'created_date'], name='classroom_course_created_idx'),
        ),
    ]
