# Generated by Django 6.0.4 on 2026-06-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_database_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='community_a_user_id_5b4d39_idx',
            old_name='application_user_accepted_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='community_a_created_f4e5a3_idx',
            old_name='application_created_idx',
        ),
        migrations.RenameIndex(
            model_name='classroom',
            new_name='community_c_course__59ecf1_idx',
            old_name='classroom_course_created_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='community_c_user_id_ab3496_idx',
            old_name='course_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='community_c_status_ad65ba_idx',
            old_name='course_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='community_l_course__9f7904_idx',
            old_name='lesson_course_created_idx',
        ),
    ]
