# Generated by Django 6.0.4 on 2026-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_certificate_options_alter_customuser_options'),
        ('community', '0002_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='studying_in',
            field=models.ManyToManyField(blank=True, related_name='users', to='community.course'),
        ),
    ]
